Vagrant.configure("2") do |config|
        config.vm.define :test01 do |node|
                node.vm.box = "base"
                node.vm.hostname = "master"
                node.vm.network :private_network, ip: "10.10.10.2", netmask: "255.255.255.0"
                node.vm.provider :virtualbox do |vb|
                        vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "test01"]
                end
                node.vm.provision "shell", path: "servidor.sh"
        end
        config.vm.define :test02 do |node|
                node.vm.box = "base"
                node.vm.hostname = "client"
                node.vm.network :private_network, ip: "10.10.10.3", netmask: "255.255.255.0"
                node.vm.provider :virtualbox do |vb|
                        vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "test02"]
                end
                node.vm.provision "shell", path: "client.sh", args: "10.10.10.2"
        end
        config.vm.define :test03 do |node|
                node.vm.box = "base"
                node.vm.hostname = "client"
                node.vm.network :private_network, ip: "10.10.10.4", netmask: "255.255.255.0"
                node.vm.provider :virtualbox do |vb|
                        vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "test03"]
                end
                node.vm.provision "shell", path: "client.sh", args: "10.10.10.2"
        end
end