
Vagrant.configure("2") do |config|
	config.vm.define :test01 do |node|
		node.vm.box = "base"
	end
	config.vm.define :test02 do |node|
		node.vm.box = "base"
	end
	config.vm.define :test03 do |node|
		node.vm.box = "base"
	end
end