Vagrant.configure("2") do |config|

    	config.vm.define :haproxy do |node|
            	node.vm.box = "base"
            	node.vm.network :private_network, ip: "10.11.12.15", netmask: "255.255.255.0"
            	node.vm.provider :virtualbox do |vb|
                    	vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "haproxy"]
            	end
            	node.vm.provision "shell", path: "haproxy.sh"
    	end

    	config.vm.define :webserver1 do |node|
            	node.vm.box = "base"
            	node.vm.network :private_network, ip: "10.11.12.16", netmask: "255.255.255.0"
            	node.vm.provider :virtualbox do |vb|
                    	vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "webserver1"]
            	end
            	node.vm.provision "shell", path: "webserver.sh", args: "webserver1 10.11.12.16"
    	end

    	config.vm.define :webserver2 do |node|
            	node.vm.box = "base"
            	node.vm.network :private_network, ip: "10.11.12.17", netmask: "255.255.255.0"
            	node.vm.provider :virtualbox do |vb|
                    	vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "webserver2"]
            	end
            	node.vm.provision "shell", path: "webserver.sh", args: "webserver2 10.11.12.17"
    	end
end